version: "{build}"

environment:
  nodejs_version: "15"
  PYTHON: "C:\\Python38-x64"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - python -V

test_script:
  - npm run test
  
artifacts:
  - path: build\package\*
